//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class User
    {
        public int UserID { get; set; }
        public string UserSurname { get; set; }
        public string UserName { get; set; }
        public string UserPatronymic { get; set; }

        private string LOGIN, PASS;
        public string UserLogin 
        { 
            get { return LOGIN; } 
            set { LOGIN = value; } 
        }

        public string UserPassword 
        {
            get { return PASS; }
            set { PASS = value; }
        }
        public int UserRole { get; set; }
    
        public virtual Role Role { get; set; }

        public User() { }
        public User(string LOGIN, string PASS)
        {
            this.LOGIN = LOGIN;
            this.PASS = PASS;
        }
    
    }
}
